# Generated by Django 6.0.2 on 2026-02-18 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('TASK', 'Tâche'), ('EVENT', 'Événement'), ('FINANCE', 'Finance'), ('PROJECT', 'Projet'), ('SYSTEM', 'Système'), ('DIGEST', 'Bilan journalier')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_tasks', models.BooleanField(default=True)),
                ('email_events', models.BooleanField(default=True)),
                ('email_daily_digest', models.BooleanField(default=True)),
                ('email_projects', models.BooleanField(default=True)),
                ('inapp_tasks', models.BooleanField(default=True)),
                ('inapp_events', models.BooleanField(default=True)),
                ('inapp_finance', models.BooleanField(default=True)),
                ('digest_time', models.TimeField(default='08:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
