# Generated by Django 6.0.2 on 2026-02-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TASK', 'Tâche'), ('EVENT', 'Événement'), ('FINANCE', 'Finance'), ('PROJECT', 'Projet'), ('SYSTEM', 'Système'), ('DIGEST', 'Bilan journalier'), ('ADVISOR', 'Conseiller Expert')], default='SYSTEM', max_length=20),
        ),
    ]
