# Generated by Django 6.0.2 on 2026-02-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='relationship_type',
            field=models.CharField(choices=[('FAMILY', 'Famille'), ('FRIEND', 'Ami(e)'), ('COLLEAGUE', 'Collègue'), ('PROFESSIONAL', 'Professionnel'), ('OTHER', 'Autre')], default='OTHER', max_length=20),
        ),
    ]
