# Generated by Django 6.0.2 on 2026-02-18 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-priority', 'due_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#87CEEB', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_minutes',
            field=models.IntegerField(default=30, help_text="Rappel avant l'événement (minutes)"),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], default='MEDIUM', max_length=10),
        ),
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_total', models.IntegerField(default=0)),
                ('events_count', models.IntegerField(default=0)),
                ('notes_created', models.IntegerField(default=0)),
                ('income_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
