# Generated by Django 6.0.2 on 2026-02-19 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_at_time', models.CharField(max_length=20)),
                ('message_type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_content', models.TextField()),
                ('is_email', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('HAPPY', 'Joyeux'), ('CONCERNED', 'Inquiet'), ('ANGRY', 'Fâché'), ('FURIOUS', 'Furieux')], default='HAPPY', max_length=20)),
                ('anger_level', models.IntegerField(default=0)),
                ('last_evaluation', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_mood', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
