# Generated by Django 6.0.2 on 2026-02-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('PERSONAL', 'Personnel'), ('WORK', 'Travail'), ('IDEA', 'Idée'), ('REMINDER', 'Rappel'), ('OTHER', 'Autre')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500, null=True),
        ),
    ]
